export const EVENTS = [
  {
    id: "11",
    title: "Core Contributor of Base Philippines",
    sentence: `Earlier today, Julius Fresco, Core Contributor of Base Philippines, shared what Base Philippines is all about and the exciting opportunities it offers! Whether you're a builder, creator, or enthusiast, there's something for you in the Base ecosystem.`,
    location: "𝗨𝗦𝗧 𝗥𝗼𝗾𝘂𝗲 𝗥𝘂𝗮𝗻𝗼 𝗘𝗻𝗴𝗶𝗻𝗲𝗲𝗿𝗶𝗻𝗴 𝗖𝗼𝗻𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗛𝗮𝗹𝗹",
    date: "February 10, 2025",
    time: "5:00 PM",
    image: "/Event/UST.jpg",
    status: "Done",
  },
  {
    id: "12",
    title: "Curious about Base?",
    sentence: `Join us for an in-depth look at the tech, trends, and opportunities. Don't miss out and register now!`,
    location: "Online",
    date: "February 13, 2025",
    time: "8:00 AM - 5:00 PM",
    image: "/Event/Ust_Engr.jpg",
    status: "Done",
  },
  {
    id: "1",
    title: "When Students Take the Lead, the Future Shines!",
    sentence: `Our Based Student, Jerome Monte, took the stage today at the ABCs of Digital Autonomy Seminar. His journey as a student leader in the space proves that the next wave of builders is already here.
Want to be a Based Student Ambassador and shape the future of Web3? Apply.`,
    location: "Online",
    date: "March 8, 2025",
    time: "7:00 PM",
    image: "/Event/WEBP/Mr.Monte.webp",
    status: "Done",
  },
  {
    id: "2",
    title: "Incredible Session at the 2025 ICpEP-NCR Caravan & Webinar Series!",
    sentence: `Our Country Lead Eli Becislao shared valuable insights on building with Base, giving attendees a deeper understanding of blockchain and its real-world applications.
Thank you to everyone who joined onsite at Adamson University and online via Zoom! Stay tuned for more learning opportunities!`,
    location: "Adamson University & Zoom",
    date: "March 12, 2025",
    time: "8:00 AM",
    image: "/Event/crop.jpg",
    status: "Done",
  },
  {
    id: "3",
    title: "Big Things Are Happening on Base!",
    sentence: `Join @basepilipinas's @0xmoonlight_ alongside Web3 leaders to discuss XION, mass adoption, and the Philippines' role in SEA.`,
    location: "Online",
    date: "March 16, 2025",
    time: "8:00 PM",
    image: "/Event/CommunityTownhall.webp",
    status: "Done",
  },
  {
    id: "4",
    title: "Filipino Web3 Spaces",
    sentence: `Filipino Web3 Spaces Presents "Building Web3: The Essential Roles of Ambassadors and Contributors" Featuring: @0xmoonlight_ @barbakusi. Don't miss this space! #FilipinoWeb3 #Web3Spaces`,
    location: "X Spaces",
    date: "March 19, 2025",
    time: "9:00 PM",
    image: "/Event/FilipinoWeb3Spaces.webp",
    status: "Done",
  },
  {
    id: "5",
    title: "The Hatch 2025: Gateway to Global Innovation",
    sentence: `Our Base Country Lead as a judge at The Hatch 2025: 𝘎𝘢𝘵𝘦𝘸𝘢𝘺 𝘵𝘰 𝘎𝘭𝘰𝘣𝘢𝘭 𝘐𝘯𝘯𝘰𝘷𝘢𝘵𝘪𝘰𝘯 𝘋𝘦𝘮𝘰 𝘋𝘢𝘺 𝘢𝘯𝘥 𝘗𝘪𝘵𝘤𝘩��𝘯𝘨 𝘊𝘰𝘮𝘱𝘦𝘵𝘪𝘵𝘪𝘰𝘯! Excited to witness groundbreaking ideas and support rising founders as they take the stage and pitch for global impact.`,
    location: "Manila",
    date: "March 21, 2025",
    time: "1:00 PM - 5:00 PM",
    image: "/Event/Hatch.webp",
    status: "Done",
  },
  {
    id: "6",
    title: "Community Townhall",
    sentence: `Marami ba kayong natutunan sa last week's Community Townhall? Kung oo, mas marami pa tayong pag-uusapan bukas! Tara, sama ka ulit sa Community Townhall — live na live sa Facebook at Twitter bukas, 8PM! Updates, announcements, at kwentuhan kasama ang buong community. Kita-kits!`,
    location: "Online - Facebook & Twitter",
    date: "March 23, 2025",
    time: "8:00 PM",
    image: "/Event/CT3.webp",
    status: "Done",
  },
  {
    id: "7",
    title: "Learn and Build on Base",
    sentence: `Learn and Build on Base. Register now!`,
    location: "Online",
    date: "March 26, 2025",
    time: "7:30 PM",
    image: "/Event/Interact.webp",
    status: "Done",
  },
  {
    id: "8",
    title: "Base Philippines Community Townhall",
    sentence: `One week in Web3 feels like a month! There's always something exciting happening, and tomorrow's Base Philippines Community Townhall is no exception. Join us as we dive into the latest updates, breakthroughs, and all things Web3! Don't miss out – see you there!`,
    location: "Online",
    date: "March 30, 2025",
    time: "8:00 PM",
    image: "/Event/CT4.webp",
    status: "Done",
  },
  {
    id: "9",
    title: "First Based Buddies in Baguio",
    sentence: `First Based Buddies in Baguio`,
    location: "Baguio City",
    date: "March 30, 2025",
    time: "All Day",
    image: "/Event/Baguio.webp",
    status: "Done",
  },
  {
    id: "10",
    title: "BasedBuddies Recap",
    sentence: `Big shoutout to everyone who made it to #BasedBuddies yesterday! Most of the attendees were beginners, but what stood out the most was their energy, curiosity, and eagerness to learn more about the Base ecosystem. It's always exciting to see fresh faces stepping into the space, hungry to build, connect, and make their mark.`,
    location: "Online",
    date: "March 30, 2025",
    time: "All Day",
    image: "/Event/BasedBuddies.webp",
    status: "Done",
  },
  {
    id: "13",
    title: "Base Learn <> Base Build @ TIP",
    sentence: `Base Learn <> Base Build is here – an initiative focused on helping you learn and build with Base. Led by Jerome Monte for the student devs of Technological Institute of the Philippines. Register now!`,
    location: "TIP (Technological Institute of the Philippines)",
    date: "April 5, 2025",
    time: "4:00 PM - 6:00 PM",
    image: "/Event/Baselearn.jpg",
    status: "Done",
  },
  {
    id: "14",
    title: "GLanca Philippines Launch",
    sentence: `Just one more day until we unveil Lanca at the GLanca Philippines event at The BLOKCSPACE! Proudly built on Base, discover cross-chain value transfer with Concero.`,
    location: "The BLOKCSPACE",
    date: "April 5, 2025",
    time: "5:00 PM - 9:00 PM",
    image: "/Event/GLanca.jpg",
    status: "Done",
  },
  {
    id: "15",
    title: "Virtual Community Townhall (April 6)",
    sentence: `Join us for another round of our Virtual Community Townhall, streamed live on Facebook and Twitter. Let's catch up, share updates, and talk about what's ahead for the community.`,
    location: "Online",
    date: "April 6, 2025",
    time: "8:00 PM",
    image: "/Event/CT5.jpg",
    status: "Done",
  },
  {
    id: "16",
    title: "Based Buddies in Makati",
    sentence: `ON-GOING: Based Buddies in Makati.`,
    location: "Makati",
    date: "April 5, 2025",
    time: "All Day",
    image: "/Event/BuddiesMakati.jpg",
    status: "Done",
  },
  {
    id: "17",
    title: "Base Learn <> Build by Ranniell",
    sentence: `Simultaneous with Based Buddies meetup, Base Learn <> Build is happening led by Ranniell Banzon.`,
    location: "Online",
    date: "April 5, 2025",
    time: "TBA",
    image: "/Event/BuddiesMeetup.jpg",
    status: "Done",
  },
  {
    id: "18",
    title: "Homebase Workshop Kickoff",
    sentence: `Base Learn <> Base Build: Homebase Workshop kicks off a 3-week online series building up to the Base Batches Buildathon.`,
    location: "Online",
    date: "April 6, 2025",
    time: "6:00 AM",
    image: "/Event/HomebaseWorkshop.jpg",
    status: "Done",
  },
  {
    id: "19",
    title: "Based Buddies in QC",
    sentence: `Yesterday's Based Buddies meetup led by Ry Ozaki (Ethereal Bliss) brought Web3 convos and community energy to QC.`,
    location: "Quezon City",
    date: "April 5, 2025",
    time: "TBA",
    image: "/Event/BasedQc.jpg",
    status: "Done",
  },
  {
    id: "20",
    title: "Based Buddies in Baguio (April)",
    sentence: `Elfritz Angelo Peralta connected with passionate attendees at Based Buddies in Baguio.`,
    location: "Baguio City",
    date: "April 5, 2025",
    time: "TBA",
    image: "/Event/BasedBaguio.jpg",
    status: "Done",
  },
  {
    id: "21",
    title: "Community Townhall (April 13)",
    sentence: `Tuloy na tuloy ang ating Community Townhall mamayang 8PM! Tara, kwentuhan tayo tungkol sa community updates at job opportunities.`,
    location: "Online",
    date: "April 13, 2025",
    time: "8:00 PM",
    image: "/Event/CT6.jpg",
    status: "Done",
  },
  {
    id: "22",
    title: "Based Buddies in Davao",
    sentence: `Thanks to Jofizim.Base.eth, Based Buddies reached Davao! One island at a time. One builder at a time.`,
    location: "Davao",
    date: "April 14, 2025",
    time: "9:00 AM",
    image: "/Event/Davao.jpg",
    status: "Done",
  },
  {
    id: "23",
    title: "Based Buddies in Laoag",
    sentence: `Thanks to Tobi, Based Buddies reached Laoag—bringing local stories and builder energy to the north.`,
    location: "Laoag",
    date: "April 12, 2025",
    time: "TBA",
    image: "/Event/Laoag.jpg",
    status: "Done",
  },
  {
    id: "24",
    title: "Community Townhall (April 21)",
    sentence: `Community Townhall originally scheduled for April 20 has been moved to April 21, 8PM. Taking time to pause and reflect this Easter.`,
    location: "Online",
    date: "April 21, 2025",
    time: "8:00 PM",
    image: "/Event/CT7.jpg",
    status: "Done",
  },
  {
    id: "25",
    title: "BASE BATCHES IRL Workshop @ ADU",
    sentence: `Adamson techies, ready to take your ideas onchain? Don't miss the BASE BATCHES IRL Workshop this May 2. Let's build, deploy, and pitch your way into the Web3 future!`,
    location: "Adamson University",
    date: "May 2, 2025",
    time: "10:00 AM - 6:00 PM",
    image: "/Event/ADU.jpg",
    status: "Done",
  },
  {
    id: "26",
    title: "Base Batches in Digos City",
    sentence: `Ready to launch your startup onchain? Join the Base Batches Workshop — a global builder event for devs, hackers, and founders. Learn. Build. Connect. Compete. Tracks: AI Agents • Stablecoins • Mini-apps • Onchain Products. Win ETH, incubator spots & a shot at $1M in Demo Day funding!`,
    location: "Mini Theater Davao del Sur State College",
    date: "May 7, 2025",
    time: "10:00 AM – 5:00 PM",
    image: "/updates/Digos.jpg",
    status: "Done",
  },
  {
    id: "27",
    title: "Base Batches in Tagum City",
    sentence: `Ready to launch your startup onchain? Join the Base Batches Workshop — a global builder event for devs, hackers, and founders. Learn. Build. Connect. Compete. Tracks: AI Agents • Stablecoins • Mini-apps • Onchain Products. Win ETH, incubator spots & a shot at $1M in Demo Day funding!`,
    location: "Mikow's Brew, Apokon Road, Tagum City",
    date: "May 8, 2025",
    time: "10:00 AM – 5:00 PM",
    image: "/updates/Tagum.jpg",
    status: "Done",
  },
  {
    id: "28",
    title: "Base Batches in Bicol",
    sentence: `Base Batches has landed in Bicol! Register now to join! Bicol University on May 8, 2025 at SILI DELI, Bicol University. Camarines Sur Polytechnic College on May 9, 2025 at CSPC Campus.`,
    location: "Bicol University & CSPC Campus",
    date: "May 8-9, 2025",
    time: "10:00 AM – 5:00 PM",
    image: "/updates/Camsur.jpg",
    status: "Done",
  },
  {
    id: "29",
    title: "Base Batch Blockchain Workshop at SIKAT-TBI",
    sentence: `Happening Now at SIKAT-TBI! The Base Batch: Blockchain Workshop is in full swing! As Bataan sets its sights on becoming the Blockchain Capital of the Philippines, we're grateful to have Mr. Elizer Rabadon, CEO of DvCode Technologies Inc. and Co-founder of Web3 Bulacan, leading today's deep dive into blockchain technology and its real-world applications.`,
    location: "SIKAT-TBI, Bataan",
    date: "May 8, 2025",
    time: "All Day",
    image: "/updates/Bataan.jpg",
    status: "Done",
  },
  {
    id: "30",
    title: "Base Batches IRL Workshop at LPU Manila",
    sentence: `LPU Manila, you showed up and showed out! The Base Batches: IRL Workshop brought together builders ready to dive into onchain dev, connect with fellow innovators, and explore what's possible with Base. Stay tuned—more IRL workshops are coming your way!`,
    location: "LPU Manila",
    date: "May 9, 2025",
    time: "All Day",
    image: "/updates/Lpu.jpg",
    status: "Done",
  },
  {
    id: "31",
    title: "Base Batches Day 2 - Tagum City",
    sentence: `Base Batches Day 2 - Tagum City with Brandless PH Davao DeFi Community. Builders continued their journey in onchain development and community building.`,
    location: "Tagum City",
    date: "May 9, 2025",
    time: "All Day",
    image: "/updates/Tagumcity.jpg",
    status: "Done",
  },
  {
    id: "32",
    title: "Base Build Recap",
    sentence: `Organized by Kyoshi, the latest Base Build gathered over 70 devs, designers, and builders for a jam-packed day of learning and hands-on building. From deploying NFTs with Hardhat to deep dives into scalable dApp architecture, participants leveled up their skills across every layer of the stack.`,
    location: "Online",
    date: "May 10, 2025",
    time: "All Day",
    image: "/updates/baserecap.jpg",
    status: "Done",
  },
  {
    id: "33",
    title: "Happy Mother's Day",
    sentence: `Happy Mother's Day to all the incredible moms building futures, nurturing dreams, and showing unstoppable strength—your love powers generations, onchain and beyond.`,
    location: "Online",
    date: "May 11, 2025",
    time: "All Day",
    image: "/updates/Mothersday.jpg",
    status: "Done",
  },
  {
    id: "34",
    title: "Based Space Event",
    sentence: `Happening Today: Based Space. What's in store at today's Based Space? Builders, creators, and enthusiasts gathered for another exciting day of learning and networking.`,
    location: "Online",
    date: "May 12, 2025",
    time: "All Day",
    image: "/updates/blue.jpg",
    status: "Done",
  },
  {
    id: "35",
    title: "Base Batches in Bulacan",
    sentence: `Another awesome Base Batches stop took place in Bulacan! Builders showed up, shared ideas, and took one step closer to shipping their projects for the Buildathon.`,
    location: "Bulacan",
    date: "May 13, 2025",
    time: "All Day",
    image: "/updates/basebulacan.jpg",
    status: "Done",
  },
  {
    id: "36",
    title: "Base Batches Global Buildathon IRL Workshop - Mindanao Leg",
    sentence: `The Mindanao leg of Base Batches: Global Buildathon IRL workshop kicked off strong at Davao Del Sur State College in Digos—first stop for onchain builders in the south!`,
    location: "Davao Del Sur State College, Digos",
    date: "May 13, 2025",
    time: "All Day",
    image: "/updates/Buildathon.jpg",
    status: "Done",
  },
  {
    id: "37",
    title: "Base Batches Day 2 - Tagum City",
    sentence: `Day 2 of Base Batches: Global Buildathon IRL workshops in Davao landed in Tagum City—where curious minds and future founders gathered to explore what it means to build on Base.`,
    location: "Tagum City",
    date: "May 9, 2025",
    time: "All Day",
    image: "/updates/tagumday2.jpg",
    status: "Done",
  },
  {
    id: "38",
    title: "Base Batches Day 3 - Davao",
    sentence: `Day 3 of the Base Batches: IRL workshops in Davao kept the energy high. Builders explored how to bring their ideas onchain, learned the ropes of the Base ecosystem, and connected with others ready to shape the future of Web3.`,
    location: "Davao",
    date: "May 9, 2025",
    time: "All Day",
    image: "/updates/Davaoday3.jpg",
    status: "Done",
  },
  {
    id: "39",
    title: "Base Batches Day 4 - Davao Final Leg",
    sentence: `The final leg of the Base Batches: Global Buildathon IRL workshops in Davao wrapped up with builders fired up and ready to take their projects onchain. From ideation to execution, the Davao community showed up strong.`,
    location: "Davao",
    date: "May 11, 2025",
    time: "All Day",
    image: "/updates/day4davao.jpg",
    status: "Done",
  },
  {
    id: "40",
    title: "CSPC Joins Base Batches Movement",
    sentence: `CSPC joined the Base Batches movement with ideas worth building on. From devs to dreamers, the energy in Camarines Sur Polytechnic Colleges was all in for onchain.`,
    location: "Camarines Sur Polytechnic Colleges",
    date: "May 9, 2025",
    time: "All Day",
    image: "/updates/devsCamsur.jpg",
    status: "Done",
  },
  {
    id: "41",
    title: "AMA with OnlyPens Project",
    sentence: `We're hosting an AMA on Base Philippines's Discord Channel featuring projects from Base Batches: Global Buildathon. First up: OnlyPens, founded by Theo Roque and Ethereal Bliss. Let's get to know their story and what they're building.`,
    location: "Discord",
    date: "May 14, 2025",
    time: "8:00 PM",
    image: "/updates/onlypens.jpg",
    status: "Done",
  },
  {
    id: "42",
    title: "Base Batches Submission Deadline",
    sentence: `Only 3 days left to submit your Base Batches entry! Builders, don't miss your shot to join the global stage, showcase what you've been working on, and take your idea further.`,
    location: "Online",
    date: "May 14, 2025",
    time: "All Day",
    image: "/updates/basebatches3.jpg",
    status: "Done",
  },
  {
    id: "43",
    title: "AMA with DeCryptify Project",
    sentence: `Tonight: We're spotlighting another local project joining Base Batches—DeCryptify! Get to know what they're building and the story behind it, hosted by our Base PH Contributor Patricia Louise.`,
    location: "Discord",
    date: "May 15, 2025",
    time: "8:00 PM",
    image: "/updates/DeCriptify.jpg",
    status: "Done",
  },
  {
    id: "44",
    title: "Base Batches Workshop at NU Dasma",
    sentence: `Base painted NU Dasma blue with the recent Base Batches: Global Buildathon workshop! Led by our Tech Lead Jerome Monte, students learned how to Build on Base, joined fun games, & pitched their projects with confidence.`,
    location: "NU Dasma",
    date: "May 15, 2025",
    time: "All Day",
    image: "/updates/nudasma.jpg",
    status: "Done",
  },
  {
    id: "45",
    title: "Based Space Awarding Ceremony",
    sentence: `Last Friday, we wrapped up Based Space with an awarding ceremony to celebrate the standout teams and moments of the week. Here's a quick rundown of the winners and why they stood out.`,
    location: "BLOKCSPACE Makati",
    date: "May 19, 2025",
    time: "All Day",
    image: "/updates/awarding.jpg",
    status: "Done",
  },
  {
    id: "46",
    title: "Based Buddies in Valenzuela",
    sentence: `Valenzuela is now BASED. At Based Buddies, builders came together, created their Base names, and took their first steps into the onchain world. More and more Filipinos are claiming their spot in Web3—starting with their own identity on Base.`,
    location: "Valenzuela",
    date: "May 21, 2025",
    time: "All Day",
    image: "/updates/Valenzuela.jpg",
    status: "Done",
  },
  {
    id: "47",
    title: "Eli Becislao at Super Vietnam 2025",
    sentence: `Scaling Builder Communities on Base. Our Country Lead Eli Becislao will be speaking at Super Vietnam 2025! Eli has been a driving force in the Philippines' crypto ecosystem since 2017 - building communities, launching ventures, and leading grassroots adoption.`,
    location: "Vietnam",
    date: "May 21, 2025",
    time: "All Day",
    image: "/updates/supereli.jpg",
    status: "Done",
  },
  {
    id: "48",
    title: "Based Buddies in GenSan",
    sentence: `GenSan, onchain vibes unlocked! Huge congrats to Aervin Gengoni, our Base contributor who brought Based Buddies to the city. Builders, students, and curious minds linked up to build on Base—proof we're reaching more cities every week.`,
    location: "General Santos City",
    date: "May 27, 2025",
    time: "All Day",
    image: "/updates/gensan.jpg",
    status: "Done",
  },
  {
    id: "49",
    title: "Based Buddies Success Story",
    sentence: `Nearly called the whole thing off, convinced the seats would stay empty. Instead, the community showed up and filled every seat. Keep showing up—support can surprise you. Congratulations, Gee Gee, on an unforgettable Based Buddies!`,
    location: "Online",
    date: "May 28, 2025",
    time: "All Day",
    image: "/updates/dripdip.jpg",
    status: "Done",
  },
  {
    id: "50",
    title: "Cryptobilis Bitcoin Pizza Party Winners",
    sentence: `Congratulations to the winners of our free tickets to the Cryptobilis Bitcoin Pizza Party! To claim your slot, kindly send us your details. See you at the party!`,
    location: "Online",
    date: "May 29, 2025",
    time: "All Day",
    image: "/updates/ticket.jpg",
    status: "Done",
  },
  {
    id: "51",
    title: "AMA with Creator Base Founder",
    sentence: `We're going live tonight at 8PM on X Space with a special AMA featuring Gagan Gehani, the founder of Creator Base! We'll talk about how Creator Base is helping creators earn onchain, how it's built on the Base ecosystem, and what's ahead for the creator economy.`,
    location: "X Spaces",
    date: "June 1, 2025",
    time: "8:00 PM",
    image: "/updates/Creatorbase.jpg",
    status: "Done",
  },
  {
    id: "52",
    title: "Post About Base Campaign",
    sentence: `POST ABOUT BASE. SIMPLE AS THAT. Filipino creators, your content matters. Whether you're posting on Facebook or TikTok, or dropping threads on X and insights on LinkedIn — every piece of content helps amplify Base in the Philippines.`,
    location: "Social Media",
    date: "June 4, 2025",
    time: "All Day",
    image: "/updates/createpost.jpg",
    status: "Done",
  },
  {
    id: "53",
    title: "Eli Becislao Arrives in Super Vietnam",
    sentence: `Touchdown Vietnam! Our Country Lead has landed in Super Vietnam! Catch him tomorrow at the panel discussion — don't miss the insights. See you there!`,
    location: "Vietnam",
    date: "June 4, 2025",
    time: "All Day",
    image: "/updates/Sirelivietnam.jpg",
    status: "Done",
  },
  {
    id: "54",
    title: "Welcome JC Pabelico",
    sentence: `Base Philippines gained a loyal contributor today. Welcome po sir JC Pabelico!`,
    location: "Online",
    date: "June 4, 2025",
    time: "All Day",
    image: "/updates/Sirjp.jpg",
    status: "Done",
  },
  {
    id: "55",
    title: "Rivalidate - Base Batches Runner-Up",
    sentence: `We've got a RUNNER-UP from the Philippines! Rivalidate is one of the standout projects in Base Batches, building a trust layer for hiring by anchoring verified credentials directly on Base. Say goodbye to résumé fraud — and hello to cryptographic proof that a candidate earned their credentials.`,
    location: "Online",
    date: "June 5, 2025",
    time: "All Day",
    image: "/updates/Rivalidate.jpg",
    status: "Done",
  },
  {
    id: "56",
    title: "Esports and AI Panel Discussion",
    sentence: `Our Base Philippines Country Lead Eli Becislao took part in an insightful panel on Esports and AI: Gaming Economy Transformation — unpacking how AI is redefining gameplay, monetization, and the future of digital competition.`,
    location: "Vietnam",
    date: "June 5, 2025",
    time: "All Day",
    image: "/updates/gamingeconomy.jpg",
    status: "Done",
  },
  {
    id: "57",
    title: "Builder Meetup with Web3 X and Securosys",
    sentence: `Our Country Lead Eli Becislao is joining another panel today at the Builder Meetup hosted by Web3 X and Securosys! This time, the spotlight's on: How Should Builders Work with Blockchain Foundations?`,
    location: "Vietnam",
    date: "June 7, 2025",
    time: "All Day",
    image: "/updates/supervietnam.jpg",
    status: "Done",
  },
  {
    id: "58",
    title: "Base Blue Social Experiment",
    sentence: `Trying out a social experiment, how far can we get in painting our timelines Base blue?`,
    location: "Social Media",
    date: "June 8, 2025",
    time: "All Day",
    image: "/updates/blue.jpg",
    status: "Done",
  },
  {
    id: "59",
    title: "Builders Meetup with Web3 X",
    sentence: `Had a great time at the Builders Meetup hosted by Web3 X! We dove into how founders and developers can better collaborate with blockchain foundations—solid insights, real talk, and sharp perspectives from fellow builders.`,
    location: "Vietnam",
    date: "June 9, 2025",
    time: "All Day",
    image: "/updates/buildermeetup.jpg",
    status: "Done",
  },
  {
    id: "60",
    title: "Base Contributors at Philippine Blockchain Week 2025",
    sentence: `Based Contributors in action at Philippine Blockchain Week 2025. Proud to see our community showing up, building connections, and representing the future of Web3 in the Philippines.`,
    location: "Manila",
    date: "June 10, 2025",
    time: "All Day",
    image: "/updates/contri.jpg",
    status: "Done",
  },
  {
    id: "61",
    title: "Base Blue Everywhere",
    sentence: `When your delulu kicks in and you start seeing Base blue everywhere.`,
    location: "Online",
    date: "June 12, 2025",
    time: "All Day",
    image: "/updates/delulu.jpg",
    status: "Done",
  },
  {
    id: "62",
    title: "Happy Father's Day",
    sentence: `Happy Father's Day to our Country Lead, Eli Becislao, and to all the incredible dads in the Base PH community. Your dedication — whether you're leading teams or raising families — keeps everything grounded and growing. We appreciate you!`,
    location: "Online",
    date: "June 15, 2025",
    time: "All Day",
    image: "/updates/fathersday.jpg",
    status: "Done",
  },
  {
    id: "63",
    title: "AMA with Scenario Protocol",
    sentence: `AMA ALERT! Get to know Scenario Protocol — the platform that lets you take control of your notifications. Want to be the first to know when something happens? Just set it, and get alerted instantly.`,
    location: "X Spaces",
    date: "June 25, 2025",
    time: "8:00 PM",
    image: "/updates/scenario.jpg",
    status: "Done",
  },
];
