export const EVENTS = [
  {
    id: "11",
    title: "Core Contributor of Base Philippines",
    sentence: `Earlier today, Julius Fresco, Core Contributor of Base Philippines, shared what Base Philippines is all about and the exciting opportunities it offers! Whether you're a builder, creator, or enthusiast, there's something for you in the Base ecosystem.`,
    location: "𝗨𝗦𝗧 𝗥𝗼𝗾𝘂𝗲 𝗥𝘂𝗮𝗻𝗼 𝗘𝗻𝗴𝗶𝗻𝗲𝗲𝗿𝗶𝗻𝗴 𝗖𝗼𝗻𝗳𝗲𝗿𝗲𝗻𝗰𝗲 𝗛𝗮𝗹𝗹",
    date: "February 10, 2025",
    time: "5:00 PM",
    image: "/Event/UST.jpg",
    status: "Done",
  },
  {
    id: "12",
    title: "Curious about Base?",
    sentence: `Join us for an in-depth look at the tech, trends, and opportunities. Don't miss out and register now!`,
    location: "Online",
    date: "February 13, 2025",
    time: "8:00 AM - 5:00 PM",
    image: "/Event/Ust_Engr.jpg",
    status: "Done",
  },
  {
    id: "1",
    title: "When Students Take the Lead, the Future Shines!",
    sentence: `Our Based Student, Jerome Monte, took the stage today at the ABCs of Digital Autonomy Seminar. His journey as a student leader in the space proves that the next wave of builders is already here.
Want to be a Based Student Ambassador and shape the future of Web3? Apply.`,
    location: "Online",
    date: "March 8, 2025",
    time: "7:00 PM",
    image: "/Event/WEBP/Mr.Monte.webp",
    status: "Done",
  },
  {
    id: "2",
    title: "Incredible Session at the 2025 ICpEP-NCR Caravan & Webinar Series!",
    sentence: `Our Country Lead Eli Becislao shared valuable insights on building with Base, giving attendees a deeper understanding of blockchain and its real-world applications.
Thank you to everyone who joined onsite at Adamson University and online via Zoom! Stay tuned for more learning opportunities!`,
    location: "Adamson University & Zoom",
    date: "March 12, 2025",
    time: "8:00 AM",
    image: "/Event/crop.jpg",
    status: "Done",
  },
  {
    id: "3",
    title: "Big Things Are Happening on Base!",
    sentence: `Join @basepilipinas's @0xmoonlight_ alongside Web3 leaders to discuss XION, mass adoption, and the Philippines' role in SEA.`,
    location: "Online",
    date: "March 16, 2025",
    time: "8:00 PM",
    image: "/Event/CommunityTownhall.webp",
    status: "Done",
  },
  {
    id: "4",
    title: "Filipino Web3 Spaces",
    sentence: `Filipino Web3 Spaces Presents "Building Web3: The Essential Roles of Ambassadors and Contributors" Featuring: @0xmoonlight_ @barbakusi. Don't miss this space! #FilipinoWeb3 #Web3Spaces`,
    location: "X Spaces",
    date: "March 19, 2025",
    time: "9:00 PM",
    image: "/Event/FilipinoWeb3Spaces.webp",
    status: "Done",
  },
  {
    id: "5",
    title: "The Hatch 2025: Gateway to Global Innovation",
    sentence: `Our Base Country Lead as a judge at The Hatch 2025: 𝘎𝘢𝘵𝘦𝘸𝘢𝘺 𝘵𝘰 𝘎𝘭𝘰𝘣𝘢𝘭 𝘐𝘯𝘯𝘰𝘷𝘢𝘵𝘪𝘰𝘯 𝘋𝘦𝘮𝘰 𝘋𝘢𝘺 𝘢𝘯𝘥 𝘗𝘪𝘵𝘤𝘩𝘪𝘯𝘨 𝘊𝘰𝘮𝘱𝘦𝘵𝘪𝘰𝘯! Excited to witness groundbreaking ideas and support rising founders as they take the stage and pitch for global impact.`,
    location: "Manila",
    date: "March 21, 2025",
    time: "1:00 PM - 5:00 PM",
    image: "/Event/Hatch.webp",
    status: "Done",
  },
  {
    id: "6",
    title: "Community Townhall",
    sentence: `Marami ba kayong natutunan sa last week's Community Townhall? Kung oo, mas marami pa tayong pag-uusapan bukas! Tara, sama ka ulit sa Community Townhall — live na live sa Facebook at Twitter bukas, 8PM! Updates, announcements, at kwentuhan kasama ang buong community. Kita-kits!`,
    location: "Online - Facebook & Twitter",
    date: "March 23, 2025",
    time: "8:00 PM",
    image: "/Event/CT3.webp",
    status: "Done",
  },
  {
    id: "7",
    title: "Learn and Build on Base",
    sentence: `Learn and Build on Base. Register now!`,
    location: "Online",
    date: "March 26, 2025",
    time: "7:30 PM",
    image: "/Event/Interact.webp",
    status: "Done",
  },
  {
    id: "8",
    title: "Base Philippines Community Townhall",
    sentence: `One week in Web3 feels like a month! There's always something exciting happening, and tomorrow's Base Philippines Community Townhall is no exception. Join us as we dive into the latest updates, breakthroughs, and all things Web3! Don't miss out – see you there!`,
    location: "Online",
    date: "March 30, 2025",
    time: "8:00 PM",
    image: "/Event/CT4.webp",
    status: "Done",
  },
  {
    id: "9",
    title: "First Based Buddies in Baguio",
    sentence: `First Based Buddies in Baguio`,
    location: "Baguio City",
    date: "March 30, 2025",
    time: "All Day",
    image: "/Event/Baguio.webp",
    status: "Done",
  },
  {
    id: "10",
    title: "BasedBuddies Recap",
    sentence: `Big shoutout to everyone who made it to #BasedBuddies yesterday! Most of the attendees were beginners, but what stood out the most was their energy, curiosity, and eagerness to learn more about the Base ecosystem. It's always exciting to see fresh faces stepping into the space, hungry to build, connect, and make their mark.`,
    location: "Online",
    date: "March 30, 2025",
    time: "All Day",
    image: "/Event/BasedBuddies.webp",
    status: "Done",
  },
  {
    id: "13",
    title: "Base Learn <> Base Build @ TIP",
    sentence: `Base Learn <> Base Build is here – an initiative focused on helping you learn and build with Base. Led by Jerome Monte for the student devs of Technological Institute of the Philippines. Register now!`,
    location: "TIP (Technological Institute of the Philippines)",
    date: "April 5, 2025",
    time: "4:00 PM - 6:00 PM",
    image: "/Event/Baselearn.jpg",
    status: "Done",
  },
  {
    id: "14",
    title: "GLanca Philippines Launch",
    sentence: `Just one more day until we unveil Lanca at the GLanca Philippines event at The BLOKCSPACE! Proudly built on Base, discover cross-chain value transfer with Concero.`,
    location: "The BLOKCSPACE",
    date: "April 5, 2025",
    time: "5:00 PM - 9:00 PM",
    image: "/Event/GLanca.jpg",
    status: "Done",
  },
  {
    id: "15",
    title: "Virtual Community Townhall (April 6)",
    sentence: `Join us for another round of our Virtual Community Townhall, streamed live on Facebook and Twitter. Let’s catch up, share updates, and talk about what’s ahead for the community.`,
    location: "Online",
    date: "April 6, 2025",
    time: "8:00 PM",
    image: "/Event/CT5.jpg",
    status: "Done",
  },
  {
    id: "16",
    title: "Based Buddies in Makati",
    sentence: `ON-GOING: Based Buddies in Makati.`,
    location: "Makati",
    date: "April 5, 2025",
    time: "All Day",
    image: "/Event/BuddiesMakati.jpg",
    status: "Done",
  },
  {
    id: "17",
    title: "Base Learn <> Build by Ranniell",
    sentence: `Simultaneous with Based Buddies meetup, Base Learn <> Build is happening led by Ranniell Banzon.`,
    location: "Online",
    date: "April 5, 2025",
    time: "TBA",
    image: "/Event/BuddiesMeetup.jpg",
    status: "Done",
  },
  {
    id: "18",
    title: "Homebase Workshop Kickoff",
    sentence: `Base Learn <> Base Build: Homebase Workshop kicks off a 3-week online series building up to the Base Batches Buildathon.`,
    location: "Online",
    date: "April 6, 2025",
    time: "6:00 AM",
    image: "/Event/HomebaseWorkshop.jpg",
    status: "Done",
  },
  {
    id: "19",
    title: "Based Buddies in QC",
    sentence: `Yesterday’s Based Buddies meetup led by Ry Ozaki (Ethereal Bliss) brought Web3 convos and community energy to QC.`,
    location: "Quezon City",
    date: "April 5, 2025",
    time: "TBA",
    image: "/Event/BasedQc.jpg",
    status: "Done",
  },
  {
    id: "20",
    title: "Based Buddies in Baguio (April)",
    sentence: `Elfritz Angelo Peralta connected with passionate attendees at Based Buddies in Baguio.`,
    location: "Baguio City",
    date: "April 5, 2025",
    time: "TBA",
    image: "/Event/BasedBaguio.jpg",
    status: "Done",
  },
  {
    id: "21",
    title: "Community Townhall (April 13)",
    sentence: `Tuloy na tuloy ang ating Community Townhall mamayang 8PM! Tara, kwentuhan tayo tungkol sa community updates at job opportunities.`,
    location: "Online",
    date: "April 13, 2025",
    time: "8:00 PM",
    image: "/Event/CT6.jpg",
    status: "Done",
  },
  {
    id: "22",
    title: "Based Buddies in Davao",
    sentence: `Thanks to Jofizim.Base.eth, Based Buddies reached Davao! One island at a time. One builder at a time.`,
    location: "Davao",
    date: "April 14, 2025",
    time: "9:00 AM",
    image: "/Event/Davao.jpg",
    status: "Done",
  },
  {
    id: "23",
    title: "Based Buddies in Laoag",
    sentence: `Thanks to Tobi, Based Buddies reached Laoag—bringing local stories and builder energy to the north.`,
    location: "Laoag",
    date: "April 12, 2025",
    time: "TBA",
    image: "/Event/Laoag.jpg",
    status: "Done",
  },
  {
    id: "24",
    title: "Community Townhall (April 21)",
    sentence: `Community Townhall originally scheduled for April 20 has been moved to April 21, 8PM. Taking time to pause and reflect this Easter.`,
    location: "Online",
    date: "April 21, 2025",
    time: "8:00 PM",
    image: "/Event/CT7.jpg",
    status: "Done",
  },
  {
    id: "25",
    title: "BASE BATCHES IRL Workshop @ ADU",
    sentence: `Adamson techies, ready to take your ideas onchain? Don’t miss the BASE BATCHES IRL Workshop this May 2. Let’s build, deploy, and pitch your way into the Web3 future!`,
    location: "Adamson University",
    date: "May 2, 2025",
    time: "10:00 AM - 6:00 PM",
    image: "/Event/ADU.jpg",
    status: "Upcoming",
  },
];
