import type { Metadata } from "next";
import Navbar from "@/components/layout/Navbar/Navbar";
import "./globals.css";
import Footer from "@/components/layout/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="mx-auto p-6">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
